### ISSUE TITLE
Bug when swipe 

### ISSUE THREAD

**Issue by vkropivko** [liangzhitao/SwipeMenuViewHolder#3]
When I slow swipe from right to left , a can scroll recyclerView up or down , confict gesture

**Comment by liangzhitao** [comment]
@vkropivko sorry,can you describe it detaily?

**Comment by vkropivko** [comment]
@liangzhitao If you swipe from right to left is not strictly a straight line that is going to fail, and the list can be a bit Scroll

**Comment by vkropivko** [comment]
@liangzhitao https://www.youtube.com/watch?v=zOOq2td-eA4

**Comment by liangzhitao** [comment]
@vkropivko I have known what did you mean. And I think , to fix this issue, we have several methods as following : 
> 1. Dealing with the `RecyclerView`( parent container )
> 2. Dealing with the `Item`(child view)

So I think I should offer the chosen to the user , and I should not put it in my library. And you can reference my solution as following

First , custom a new RecyclerView 
```Java
public class MyRecyclerView extends RecyclerView {
    private GestureDetector mGestureDetector;

    public MyRecyclerView(Context context) {
        super(context);
    }

    public MyRecyclerView(Context context, @Nullable AttributeSet attrs) {
        super(context, attrs);
        mGestureDetector = new GestureDetector(context, new YScrollDetector());
        setFadingEdgeLength(0);
    }

    public MyRecyclerView(Context context, @Nullable AttributeSet attrs, int defStyle) {
        super(context, attrs, defStyle);
    }

    @Override
    public boolean onInterceptTouchEvent(MotionEvent e) {
        return super.onInterceptTouchEvent(e) && mGestureDetector.onTouchEvent(e);
    }

    class YScrollDetector extends GestureDetector.SimpleOnGestureListener {
        @Override
        public boolean onScroll(MotionEvent e1, MotionEvent e2, float distanceX, float distanceY) {
            return Math.abs(distanceY) >= Math.abs(distanceX);
        }
    }
}
```
Then, use it in the `Activity` or `Fragment`
```Java
MyRecyclerView recyclerView = (MyRecyclerView) findViewById(R.id.recyclerview);
```

And I put the it in my sample, you can sync the code to figure it out.

**Comment by vkropivko** [comment]
@liangzhitao Thanks , in Monday I try this , and send feedback to you

**Comment by liangzhitao** [comment]
@vkropivko OK, enjoy weekend first :-)

**Comment by vkropivko** [comment]
Very Good , https://play.google.com/store/apps/details?id=com.textra&hl=ru
this example perfect work , you can do the same?

**Comment by liangzhitao** [comment]
@vkropivko Thank you for your recommendation . The app is quite awesome. What do you want is the effection of bouncing ? Facebook offer a good practice. [rebound](https://github.com/facebook/rebound).
And then , I close this issue.

**Comment by vkropivko** [comment]
@liangzhitao 
I need the same behavior in this program. When I start to swipe , block vertical to scroll in the application that I showed .
It would be a perfect job this library
